test: compareFiles.o
		cc -o test compareFiles.o
compareFiles.o: compareFiles.c
					 cc -c compareFiles.c
#test_cpp: compareFiles_cpp.o
#			 g++ -o test_cpp compareFiles_cpp.o
#compareFiles_cpp.o: compareFiles_cpp.cpp
#						  g++ -c compareFiles_cpp.cpp
clean:
		rm -rf test compareFiles.o
#		rm -rf test_cpp compareFiles_cpp.o
